# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sensor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='time_period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
