# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-18 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sensor_time_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='time_period',
        ),
        migrations.AddField(
            model_name='device',
            name='time_period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
